### PR TITLE
Mac Installation

### PR DESCRIPTION
**Pull request by ranrinc**
Botman MacOS installation

### CODE REVIEW

**Comment by ranrinc** [comment]
@mpociot finally have time to do macOS installation readme. Hope this can be merge into your documentation for botman.

**Comment by johntiror** [comment]
As described here https://github.com/botman/botman/blob/master/CONTRIBUTING.md please squash the commits. 
I would avoid using phrases like "In my case" they're not optimal for docs.

**Comment by ranrinc** [comment]
Alright doing some rewrite and hope this is OK

**Comment by mpociot** [comment]
@ranrinc Thank you for your PR - even though the information is useful, I do not feel like this fits into the official BotMan documentation.

Maybe it would make more sense as a personal blog post?

**Pull request closed without merging**
